version: "3.8"

services:
  db:
    hostname: sql-db
    build:
      context: .
      dockerfile: /home/mng/task5_docker/Dockerfile.db
    container_name: db
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - /db_data:/var/lib/mysql
    deploy: 
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${MYSQL_DB_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=${ROOT_HOST}
    networks:
      backend:
        ipv4_address: 172.20.0.10


  web:
    hostname: web
    build:
      context: .
      dockerfile: /home/mng/task5_docker/Dockerfile.python
    container_name: web
    restart: always
    depends_on:
      - db
    links:
      - "db"
    deploy:
    environment:
      - DB_NAME=${DATABASE_NAME}
      - DB_USER=${MYSQL_DB_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=${HOST}
    networks:
      backend:
        ipv4_address: 172.20.0.5



  reverse-proxy:
    hostname: reverse-proxy
    build:
      context: .
      dockerfile: /home/mng/task5_docker/yamlik2/Dockerfile.haproxy
    container_name: reverse-proxy
    depends_on:
      - "web"
    restart: on-failure:5
    deploy:
    networks:
        backend: {}
    ports:
    - "127.0.0.1:8080:8080"
    volumes:
    - /home/mng/task5_docker/yamlik2/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:rw 


  ingress-proxy:
    hostname: ingress-proxy
    build:
      context: .
      dockerfile: /home/mng/task5_docker/yamlik2/Dockerfile.nginx
    container_name: ingress-proxy
    depends_on:
    - "reverse-proxy"
    restart: on-failure:5
    network_mode: host
    deploy:
    volumes:
    - /home/mng/task5_docker/yamlik2/default.conf:/etc/nginx/conf.d/default.conf:rw
    - /home/mng/task5_docker/yamlik2/nginx.conf:/etc/nginx/nginx.conf:rw


networks:
  backend:
    name: backend
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

  
    